# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailuser', 'django_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='emailuser.EmailUser'),
        ),
    ]
